language: csharp
solution: InsideTradeRegistry.sln
mono: none
dotnet: 2.2
dist: xenial
script:
 - dotnet build -c Release
 - dotnet test InsideTradeRegistry.Api.Test/ -c Release
deploy:
 skip_cleanup: true
 provider: script
 script: bash upload_nuget.sh 
 on:
   branch: deploy_nuget